# Generated by Django 4.0.2 on 2022-02-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
